iex "choco install firefox -y"
iex "choco install 7zip -y"
iex "choco install sdelete -y"
iex "choco install ultradefrag -y"
iex "choco install sourcetree -y"
iex "choco install notepadplusplus -y"
iex "choco install visualstudio2017community -y -timeout 10800"